export const testsRules = [
  { kind: "test.begin", coreDelta: { arousal: 0.18 }, appraisalDelta: { uncertainty: 0.18, effort: 0.12 }, tendencyDelta: { verify: 0.35 }, tags: ["focused", "expectant"], cause: "tests started", defaultPriority: 0.6, ttlMs: 8000 },
  { kind: "test.pass", coreDelta: { valence: 0.45, dominance: 0.35, arousal: -0.20 }, appraisalDelta: { goalProgress: 0.55, competence: 0.45, goalBlockage: -0.30, uncertainty: -0.20, risk: -0.15 }, tendencyDelta: { celebrate: 0.35, approach: 0.20, repair: -0.25, guard: -0.15, investigate: -0.10 }, tags: ["relieved", "proud", "satisfied"], cause: "tests passed", defaultPriority: 0.8, ttlMs: 10000 },
  { kind: "test.fail", coreDelta: { valence: -0.25, arousal: 0.28, dominance: -0.18 }, appraisalDelta: { goalBlockage: 0.40, competence: -0.18 }, tendencyDelta: { repair: 0.35, investigate: 0.25 }, tags: ["concerned", "frustrated"], cause: "tests failed", defaultPriority: 0.85, ttlMs: 10000 },
  { kind: "build.begin", coreDelta: { arousal: 0.15 }, appraisalDelta: { effort: 0.18, uncertainty: 0.12 }, tendencyDelta: { verify: 0.30 }, tags: ["focused"], cause: "build started", defaultPriority: 0.5, ttlMs: 8000 },
  { kind: "build.success", coreDelta: { valence: 0.40, dominance: 0.30, arousal: -0.15 }, appraisalDelta: { goalProgress: 0.50, competence: 0.35, goalBlockage: -0.25, uncertainty: -0.15 }, tendencyDelta: { celebrate: 0.25, approach: 0.15, repair: -0.20, guard: -0.10 }, tags: ["satisfied", "content", "relieved"], cause: "build succeeded", defaultPriority: 0.75, ttlMs: 10000 },
  { kind: "build.failure", coreDelta: { valence: -0.25, arousal: 0.30, dominance: -0.20 }, appraisalDelta: { goalBlockage: 0.45 }, tendencyDelta: { repair: 0.35, investigate: 0.25 }, tags: ["strained"], cause: "build failed", defaultPriority: 0.85, ttlMs: 10000 },
  { kind: "git.diff", coreDelta: { arousal: 0.06 }, appraisalDelta: { uncertainty: 0.06 }, tendencyDelta: { investigate: 0.12 }, tags: ["observant"], cause: "git diff", defaultPriority: 0.3, ttlMs: 5000 },
  { kind: "git.commit", coreDelta: { valence: 0.15, dominance: 0.12 }, appraisalDelta: { goalProgress: 0.20, controllability: 0.15 }, tendencyDelta: { approach: 0.15 }, tags: ["content", "organized"], cause: "git commit", defaultPriority: 0.5, ttlMs: 8000 },
  { kind: "git.conflict", coreDelta: { valence: -0.28, arousal: 0.30, dominance: -0.28 }, appraisalDelta: { goalBlockage: 0.50, uncertainty: 0.30 }, tendencyDelta: { repair: 0.40, investigate: 0.25, guard: 0.15 }, tags: ["tense", "guarded"], cause: "git conflict", defaultPriority: 0.9, ttlMs: 12000 },
];
