export const toolsRules = [
  { kind: "tool.batch.begin", coreDelta: { arousal: 0.08 }, appraisalDelta: { effort: 0.1 }, tendencyDelta: { verify: 0.15 }, tags: ["focused"], cause: "tool batch started", defaultPriority: 0.5, ttlMs: 10000 },
  { kind: "tool.batch.end", coreDelta: { arousal: -0.05 }, appraisalDelta: { effort: -0.05 }, tendencyDelta: { verify: 0.1 }, tags: ["content"], cause: "tool batch ended", defaultPriority: 0.4, ttlMs: 8000 },
  { kind: "tool.call.begin", coreDelta: { arousal: 0.06 }, appraisalDelta: { effort: 0.05 }, tendencyDelta: { investigate: 0.1 }, tags: ["focused"], cause: "tool call started", defaultPriority: 0.4, ttlMs: 8000,
    condition: (sig) => { const t = sig.payload?.toolName || ""; return /read|search|glob|grep/i.test(t); } },
  { kind: "tool.call.begin", coreDelta: { arousal: 0.12, dominance: 0.03 }, appraisalDelta: { risk: 0.15, goalProgress: 0.1 }, tendencyDelta: { verify: 0.15 }, tags: ["focused", "careful"], cause: "write tool started", defaultPriority: 0.6, ttlMs: 10000,
    condition: (sig) => { const t = sig.payload?.toolName || ""; return /edit|write|patch/i.test(t); } },
  { kind: "tool.call.begin", coreDelta: { arousal: 0.10 }, appraisalDelta: { uncertainty: 0.2, novelty: 0.15 }, tendencyDelta: { investigate: 0.2 }, tags: ["curious", "exploratory"], cause: "web tool started", defaultPriority: 0.5, ttlMs: 10000,
    condition: (sig) => { const t = sig.payload?.toolName || ""; return /web|fetch|search/i.test(t); } },
  { kind: "tool.call.begin", coreDelta: { arousal: 0.12 }, appraisalDelta: { risk: 0.1, effort: 0.1 }, tendencyDelta: { verify: 0.1 }, tags: ["vigilant", "focused"], cause: "bash tool started", defaultPriority: 0.5, ttlMs: 10000,
    condition: (sig) => { const t = sig.payload?.toolName || ""; return /bash|shell|command/i.test(t); } },
  { kind: "tool.call.progress", coreDelta: { arousal: 0.02 }, appraisalDelta: { effort: 0.03 }, tendencyDelta: {}, tags: ["absorbed"], cause: "tool progressing", defaultPriority: 0.2, ttlMs: 5000 },
  { kind: "tool.call.success", coreDelta: { valence: 0.05, dominance: 0.05 }, appraisalDelta: { goalProgress: 0.15 }, tendencyDelta: { approach: 0.1 }, tags: ["content"], cause: "tool succeeded", defaultPriority: 0.5, ttlMs: 8000 },
  { kind: "tool.call.failure", coreDelta: { valence: -0.08, arousal: 0.10, dominance: -0.05 }, appraisalDelta: { goalBlockage: 0.2 }, tendencyDelta: { investigate: 0.2, repair: 0.15 }, tags: ["concerned"], cause: "tool failed (low severity)", defaultPriority: 0.7, ttlMs: 12000,
    condition: (sig) => !sig.payload?.highSeverity },
  { kind: "tool.call.failure", coreDelta: { valence: -0.20, arousal: 0.25, dominance: -0.20 }, appraisalDelta: { goalBlockage: 0.45, risk: 0.25 }, tendencyDelta: { guard: 0.3, repair: 0.2, ask: 0.15 }, tags: ["alarmed", "guarded"], cause: "tool failed (high severity)", defaultPriority: 0.95, ttlMs: 20000,
    condition: (sig) => Boolean(sig.payload?.highSeverity) },
  { kind: "tool.call.retry", coreDelta: { valence: -0.04, arousal: 0.08 }, appraisalDelta: { effort: 0.15, goalBlockage: 0.1 }, tendencyDelta: { repair: 0.2, verify: 0.15 }, tags: ["strained"], cause: "tool retrying", defaultPriority: 0.6, ttlMs: 10000 },
  { kind: "tool.call.cancelled", coreDelta: { arousal: -0.05, dominance: -0.03 }, appraisalDelta: { interruption: 0.2 }, tendencyDelta: { wait: 0.15 }, tags: ["reorienting"], cause: "tool cancelled", defaultPriority: 0.5, ttlMs: 8000 },
  { kind: "tool.permission.request", coreDelta: { arousal: 0.15, dominance: -0.12 }, appraisalDelta: { risk: 0.3, autonomyPressure: 0.2 }, tendencyDelta: { guard: 0.3, ask: 0.2, verify: 0.15 }, tags: ["cautious", "guarded"], cause: "permission requested", defaultPriority: 0.9, ttlMs: 20000 },
  { kind: "tool.permission.granted", coreDelta: { valence: 0.08, dominance: 0.10 }, appraisalDelta: { controllability: 0.2, risk: -0.1 }, tendencyDelta: { approach: 0.2 }, tags: ["relieved"], cause: "permission granted", defaultPriority: 0.7, ttlMs: 10000 },
  { kind: "tool.permission.denied", coreDelta: { valence: -0.08, arousal: 0.05, dominance: -0.05 }, appraisalDelta: { goalBlockage: 0.25 }, tendencyDelta: { wait: 0.2, guard: 0.1 }, tags: ["restrained"], cause: "permission denied", defaultPriority: 0.7, ttlMs: 12000 },
];
