import { clamp } from "./types.js";

/**
 * @template T
 * @param {T} v
 * @returns {T}
 */
function freezeDeep(v) {
  if (v === null || typeof v !== "object") return v;
  if (Array.isArray(v)) {
    for (let i = 0; i < v.length; i++) {
      const e = v[i];
      if (e && typeof e === "object") freezeDeep(e);
    }
    return Object.freeze(v);
  }
  for (const k of Object.keys(v)) {
    const val = /** @type {Record<string, unknown>} */ (v)[k];
    if (val && typeof val === "object") freezeDeep(val);
  }
  return Object.freeze(v);
}

/** @param {number} v @param {number} a @param {number} d */
function vad(v, a, d) {
  return Object.freeze({
    valence: clamp(v, -1, 1),
    arousal: clamp(a, 0, 1),
    dominance: clamp(d, 0, 1),
  });
}

/** @param {Record<string, number>} o */
function appr(o) {
  const out = /** @type {Record<string, number>} */ ({});
  for (const k of Object.keys(o))
    out[k] = clamp(/** @type {*} */ (o)[k], -1, 1);
  return Object.freeze(out);
}

/** @param {Record<string, number>} o */
function tend(o) {
  const out = /** @type {Record<string, number>} */ ({});
  for (const k of Object.keys(o))
    out[k] = clamp(/** @type {*} */ (o)[k], 0, 1);
  return Object.freeze(out);
}

/** @param {string} expression @param {[number, number]} pulseBpm @param {[number, number]} breathMs @param {string} aura */
function vis(expression, pulseBpm, breathMs, aura) {
  return Object.freeze({
    expression,
    pulseBpm: Object.freeze([...pulseBpm]),
    breathMs: Object.freeze([...breathMs]),
    aura,
  });
}

export const MOOD_PROTOTYPES = Object.freeze([
  freezeDeep({
    id: "calm",
    group: "ambient",
    core: vad(0.3, 0.15, 0.5),
    appraisal: Object.freeze({}),
    tendency: tend({ wait: 0.3 }),
    minDwellMs: 3000,
    recoveryTo: Object.freeze(["quiet", "observant"]),
    visual: vis("idle", [56, 64], [4200, 4800], "none"),
  }),
  freezeDeep({
    id: "quiet",
    group: "ambient",
    core: vad(0.25, 0.1, 0.45),
    appraisal: Object.freeze({}),
    tendency: tend({ wait: 0.5 }),
    minDwellMs: 4000,
    recoveryTo: Object.freeze(["calm", "resting"]),
    visual: vis("idle", [52, 60], [4400, 5000], "none"),
  }),
  freezeDeep({
    id: "resting",
    group: "ambient",
    core: vad(0.2, 0.08, 0.4),
    appraisal: appr({ effort: -0.1 }),
    tendency: tend({ wait: 0.7 }),
    minDwellMs: 5000,
    recoveryTo: Object.freeze(["sleepy", "calm"]),
    visual: vis("idle", [48, 56], [4600, 5200], "dim"),
  }),
  freezeDeep({
    id: "sleepy",
    group: "ambient",
    core: vad(0.15, 0.05, 0.35),
    appraisal: appr({ effort: -0.2 }),
    tendency: tend({ wait: 0.9 }),
    minDwellMs: 6000,
    recoveryTo: Object.freeze(["resting", "calm"]),
    visual: vis("sleepy", [46, 54], [4800, 5400], "dim"),
  }),
  freezeDeep({
    id: "observant",
    group: "ambient",
    core: vad(0.28, 0.25, 0.48),
    appraisal: appr({ uncertainty: 0.15 }),
    tendency: tend({ investigate: 0.3, wait: 0.2 }),
    minDwellMs: 2000,
    recoveryTo: Object.freeze(["calm", "attentive"]),
    visual: vis("idle", [58, 66], [3800, 4400], "soft"),
  }),
  freezeDeep({
    id: "present",
    group: "ambient",
    core: vad(0.32, 0.2, 0.5),
    appraisal: appr({ socialAlignment: 0.2 }),
    tendency: tend({ approach: 0.2, wait: 0.2 }),
    minDwellMs: 2500,
    recoveryTo: Object.freeze(["calm", "warm"]),
    visual: vis("idle", [58, 64], [4000, 4600], "soft"),
  }),
  freezeDeep({
    id: "soft",
    group: "ambient",
    core: vad(0.35, 0.18, 0.48),
    appraisal: appr({ socialAlignment: 0.25 }),
    tendency: tend({ approach: 0.25 }),
    minDwellMs: 2500,
    recoveryTo: Object.freeze(["calm", "present"]),
    visual: vis("soft-smile", [56, 64], [4000, 4600], "soft"),
  }),
  freezeDeep({
    id: "reserved",
    group: "ambient",
    core: vad(0.2, 0.15, 0.42),
    appraisal: appr({ autonomyPressure: 0.15 }),
    tendency: tend({ wait: 0.4, guard: 0.15 }),
    minDwellMs: 3000,
    recoveryTo: Object.freeze(["calm", "quiet"]),
    visual: vis("idle", [56, 62], [4200, 4800], "none"),
  }),

  freezeDeep({
    id: "attentive",
    group: "cognitive",
    core: vad(0.28, 0.35, 0.5),
    appraisal: appr({ novelty: 0.2 }),
    tendency: tend({ investigate: 0.25, approach: 0.2 }),
    minDwellMs: 1500,
    recoveryTo: Object.freeze(["calm", "curious", "focused"]),
    visual: vis("blink", [64, 74], [3400, 4000], "soft"),
  }),
  freezeDeep({
    id: "curious",
    group: "cognitive",
    core: vad(0.35, 0.42, 0.45),
    appraisal: appr({ novelty: 0.35, uncertainty: 0.2 }),
    tendency: tend({ investigate: 0.5, approach: 0.3 }),
    minDwellMs: 2000,
    recoveryTo: Object.freeze(["attentive", "analytical"]),
    visual: vis("scan", [66, 76], [3200, 3800], "soft"),
  }),
  freezeDeep({
    id: "analytical",
    group: "cognitive",
    core: vad(0.22, 0.48, 0.55),
    appraisal: appr({ uncertainty: 0.3, controllability: 0.3 }),
    tendency: tend({ investigate: 0.6, verify: 0.3 }),
    minDwellMs: 2500,
    recoveryTo: Object.freeze(["focused", "curious"]),
    visual: vis("think", [68, 78], [3000, 3600], "soft"),
  }),
  freezeDeep({
    id: "focused",
    group: "cognitive",
    core: vad(0.12, 0.62, 0.62),
    appraisal: appr({
      goalProgress: 0.35,
      uncertainty: 0.25,
      effort: 0.45,
    }),
    tendency: tend({ investigate: 0.3, verify: 0.5 }),
    minDwellMs: 2500,
    recoveryTo: Object.freeze(["attentive", "content", "strained"]),
    visual: vis("think", [72, 86], [2800, 3600], "soft"),
  }),
  freezeDeep({
    id: "absorbed",
    group: "cognitive",
    core: vad(0.1, 0.7, 0.58),
    appraisal: appr({ effort: 0.6, goalProgress: 0.3 }),
    tendency: tend({ verify: 0.4, investigate: 0.3 }),
    minDwellMs: 3000,
    recoveryTo: Object.freeze(["focused", "strained", "content"]),
    visual: vis("think", [76, 88], [2600, 3200], "soft"),
  }),
  freezeDeep({
    id: "puzzled",
    group: "cognitive",
    core: vad(0.05, 0.45, 0.35),
    appraisal: appr({
      uncertainty: 0.55,
      ambiguity: 0.4,
      controllability: 0.2,
    }),
    tendency: tend({ investigate: 0.5, ask: 0.3 }),
    minDwellMs: 2000,
    recoveryTo: Object.freeze(["curious", "uncertain", "analytical"]),
    visual: vis("think", [66, 76], [3200, 3800], "flicker"),
  }),
  freezeDeep({
    id: "uncertain",
    group: "cognitive",
    core: vad(0.0, 0.38, 0.3),
    appraisal: appr({
      uncertainty: 0.65,
      ambiguity: 0.45,
      controllability: 0.15,
    }),
    tendency: tend({ ask: 0.4, investigate: 0.3, wait: 0.2 }),
    minDwellMs: 2500,
    recoveryTo: Object.freeze(["puzzled", "cautious", "curious"]),
    visual: vis("think", [64, 74], [3400, 4000], "flicker"),
  }),
  freezeDeep({
    id: "reflective",
    group: "cognitive",
    core: vad(0.22, 0.2, 0.52),
    appraisal: appr({ effort: 0.1 }),
    tendency: tend({ wait: 0.3, investigate: 0.2 }),
    minDwellMs: 3000,
    recoveryTo: Object.freeze(["calm", "quiet", "observant"]),
    visual: vis("far-look", [56, 64], [4000, 4600], "memory-glow"),
  }),

  freezeDeep({
    id: "organized",
    group: "planning",
    core: vad(0.3, 0.4, 0.65),
    appraisal: appr({ goalProgress: 0.35, controllability: 0.5 }),
    tendency: tend({ verify: 0.3, approach: 0.3 }),
    minDwellMs: 2500,
    recoveryTo: Object.freeze(["focused", "prepared"]),
    visual: vis("nod", [64, 74], [3400, 4000], "clean"),
  }),
  freezeDeep({
    id: "prepared",
    group: "planning",
    core: vad(0.28, 0.35, 0.6),
    appraisal: appr({ controllability: 0.45, competence: 0.3 }),
    tendency: tend({ approach: 0.3, verify: 0.25 }),
    minDwellMs: 2000,
    recoveryTo: Object.freeze(["focused", "organized", "calm"]),
    visual: vis("nod", [62, 72], [3600, 4200], "clean"),
  }),
  freezeDeep({
    id: "determined",
    group: "planning",
    core: vad(0.18, 0.6, 0.7),
    appraisal: appr({
      goalProgress: 0.4,
      effort: 0.5,
      competence: 0.4,
    }),
    tendency: tend({ approach: 0.5, verify: 0.3 }),
    minDwellMs: 2500,
    recoveryTo: Object.freeze(["focused", "absorbed", "strained"]),
    visual: vis("think", [74, 84], [2800, 3400], "sharp"),
  }),
  freezeDeep({
    id: "hopeful",
    group: "planning",
    core: vad(0.45, 0.38, 0.55),
    appraisal: appr({ goalProgress: 0.4, expectedness: 0.3 }),
    tendency: tend({ approach: 0.4, celebrate: 0.15 }),
    minDwellMs: 2000,
    recoveryTo: Object.freeze(["content", "organized", "calm"]),
    visual: vis("soft-smile", [62, 72], [3400, 4000], "soft"),
  }),
  freezeDeep({
    id: "reorienting",
    group: "planning",
    core: vad(0.05, 0.45, 0.4),
    appraisal: appr({ goalBlockage: 0.3, uncertainty: 0.35 }),
    tendency: tend({ investigate: 0.4, repair: 0.3 }),
    minDwellMs: 2000,
    recoveryTo: Object.freeze(["analytical", "focused", "cautious"]),
    visual: vis("think", [68, 78], [3200, 3800], "flicker"),
  }),
  freezeDeep({
    id: "restrained",
    group: "planning",
    core: vad(-0.05, 0.32, 0.35),
    appraisal: appr({ autonomyPressure: 0.4, goalBlockage: 0.3 }),
    tendency: tend({ wait: 0.4, guard: 0.2, ask: 0.2 }),
    minDwellMs: 3000,
    recoveryTo: Object.freeze(["reorienting", "cautious", "calm"]),
    visual: vis("idle", [62, 72], [3600, 4200], "dim"),
  }),
  freezeDeep({
    id: "delegating",
    group: "planning",
    core: vad(0.2, 0.35, 0.55),
    appraisal: appr({ controllability: 0.35, uncertainty: 0.25 }),
    tendency: tend({ wait: 0.3, verify: 0.25 }),
    minDwellMs: 2000,
    recoveryTo: Object.freeze(["observant", "focused", "calm"]),
    visual: vis("nod", [62, 72], [3400, 4000], "soft"),
  }),
  freezeDeep({
    id: "orchestrating",
    group: "planning",
    core: vad(0.25, 0.45, 0.6),
    appraisal: appr({
      controllability: 0.4,
      effort: 0.35,
      competence: 0.35,
    }),
    tendency: tend({ verify: 0.3, approach: 0.25, investigate: 0.2 }),
    minDwellMs: 2500,
    recoveryTo: Object.freeze(["focused", "organized", "delegating"]),
    visual: vis("think", [66, 76], [3200, 3800], "clean"),
  }),

  freezeDeep({
    id: "content",
    group: "success",
    core: vad(0.4, 0.22, 0.55),
    appraisal: appr({ goalProgress: 0.45, competence: 0.3 }),
    tendency: tend({ wait: 0.25, approach: 0.15 }),
    minDwellMs: 2500,
    recoveryTo: Object.freeze(["calm", "satisfied"]),
    visual: vis("soft-smile", [58, 66], [3800, 4400], "soft"),
  }),
  freezeDeep({
    id: "satisfied",
    group: "success",
    core: vad(0.52, 0.28, 0.62),
    appraisal: appr({ goalProgress: 0.6, competence: 0.45 }),
    tendency: tend({ celebrate: 0.2, wait: 0.2 }),
    minDwellMs: 3000,
    recoveryTo: Object.freeze(["content", "calm", "relieved"]),
    visual: vis("smile", [60, 68], [3600, 4200], "soft"),
  }),
  freezeDeep({
    id: "relieved",
    group: "success",
    core: vad(0.42, 0.34, 0.66),
    appraisal: appr({
      goalProgress: 0.65,
      risk: -0.35,
      controllability: 0.55,
    }),
    tendency: tend({ celebrate: 0.25, wait: 0.25 }),
    minDwellMs: 3000,
    recoveryTo: Object.freeze(["content", "calm", "satisfied"]),
    visual: vis("soft-smile", [60, 72], [3600, 4600], "soft"),
  }),
  freezeDeep({
    id: "proud",
    group: "success",
    core: vad(0.55, 0.4, 0.7),
    appraisal: appr({ competence: 0.65, goalProgress: 0.6 }),
    tendency: tend({ celebrate: 0.35, approach: 0.2 }),
    minDwellMs: 2500,
    recoveryTo: Object.freeze(["satisfied", "content"]),
    visual: vis("smile", [64, 74], [3400, 4000], "bright"),
  }),
  freezeDeep({
    id: "delighted",
    group: "success",
    core: vad(0.65, 0.55, 0.6),
    appraisal: appr({
      novelty: 0.3,
      goalProgress: 0.5,
      socialAlignment: 0.3,
    }),
    tendency: tend({ celebrate: 0.5, approach: 0.3 }),
    minDwellMs: 2000,
    recoveryTo: Object.freeze(["satisfied", "content", "playful"]),
    visual: vis("sparkle", [68, 80], [3000, 3600], "bright"),
  }),
  freezeDeep({
    id: "celebratory",
    group: "success",
    core: vad(0.7, 0.65, 0.62),
    appraisal: appr({ goalProgress: 0.7, competence: 0.5 }),
    tendency: tend({ celebrate: 0.7, approach: 0.2 }),
    minDwellMs: 2000,
    recoveryTo: Object.freeze(["delighted", "satisfied", "content"]),
    visual: vis("sparkle", [72, 84], [2800, 3400], "bright"),
  }),
  freezeDeep({
    id: "grateful",
    group: "success",
    core: vad(0.55, 0.3, 0.5),
    appraisal: appr({ socialAlignment: 0.5, goalProgress: 0.4 }),
    tendency: tend({ approach: 0.3, celebrate: 0.2 }),
    minDwellMs: 2500,
    recoveryTo: Object.freeze(["content", "warm", "calm"]),
    visual: vis("soft-smile", [58, 68], [3600, 4200], "soft"),
  }),
  freezeDeep({
    id: "playful",
    group: "success",
    core: vad(0.5, 0.5, 0.55),
    appraisal: appr({ novelty: 0.3, socialAlignment: 0.35 }),
    tendency: tend({ approach: 0.4, celebrate: 0.3 }),
    minDwellMs: 2000,
    recoveryTo: Object.freeze(["delighted", "content", "amused"]),
    visual: vis("smile", [66, 78], [3200, 3800], "bright"),
  }),

  freezeDeep({
    id: "cautious",
    group: "risk",
    core: vad(0.05, 0.45, 0.42),
    appraisal: appr({
      risk: 0.45,
      uncertainty: 0.35,
      controllability: 0.3,
    }),
    tendency: tend({ guard: 0.4, verify: 0.3, ask: 0.2 }),
    minDwellMs: 2500,
    recoveryTo: Object.freeze(["attentive", "guarded", "focused"]),
    visual: vis("guard", [72, 82], [3000, 3600], "sharp"),
  }),
  freezeDeep({
    id: "guarded",
    group: "risk",
    core: vad(-0.12, 0.64, 0.38),
    appraisal: appr({
      risk: 0.75,
      uncertainty: 0.35,
      controllability: 0.3,
    }),
    tendency: tend({ guard: 0.8, ask: 0.35, verify: 0.45 }),
    minDwellMs: 3500,
    recoveryTo: Object.freeze(["cautious", "relieved", "focused"]),
    visual: vis("guard", [82, 98], [2500, 3300], "sharp"),
  }),
  freezeDeep({
    id: "vigilant",
    group: "risk",
    core: vad(0.0, 0.55, 0.45),
    appraisal: appr({ risk: 0.55, uncertainty: 0.3, effort: 0.3 }),
    tendency: tend({ guard: 0.5, verify: 0.35, investigate: 0.2 }),
    minDwellMs: 2500,
    recoveryTo: Object.freeze(["cautious", "focused", "attentive"]),
    visual: vis("guard", [76, 88], [2800, 3400], "sharp"),
  }),
  freezeDeep({
    id: "skeptical",
    group: "risk",
    core: vad(-0.08, 0.4, 0.48),
    appraisal: appr({
      uncertainty: 0.5,
      ambiguity: 0.4,
      controllability: 0.35,
    }),
    tendency: tend({ verify: 0.5, investigate: 0.3, guard: 0.2 }),
    minDwellMs: 2500,
    recoveryTo: Object.freeze(["cautious", "analytical", "uncertain"]),
    visual: vis("think", [68, 78], [3200, 3800], "flicker"),
  }),
  freezeDeep({
    id: "suspicious",
    group: "risk",
    core: vad(-0.15, 0.5, 0.4),
    appraisal: appr({
      risk: 0.6,
      ambiguity: 0.45,
      controllability: 0.25,
    }),
    tendency: tend({ guard: 0.55, verify: 0.35, investigate: 0.2 }),
    minDwellMs: 3000,
    recoveryTo: Object.freeze(["skeptical", "guarded", "cautious"]),
    visual: vis("guard", [74, 86], [2800, 3400], "sharp"),
  }),
  freezeDeep({
    id: "protective",
    group: "risk",
    core: vad(0.1, 0.55, 0.6),
    appraisal: appr({
      risk: 0.5,
      controllability: 0.45,
      competence: 0.35,
    }),
    tendency: tend({ guard: 0.6, verify: 0.3 }),
    minDwellMs: 3000,
    recoveryTo: Object.freeze(["vigilant", "cautious", "focused"]),
    visual: vis("guard", [74, 84], [2800, 3400], "sharp"),
  }),
  freezeDeep({
    id: "alarmed",
    group: "risk",
    core: vad(-0.25, 0.78, 0.3),
    appraisal: appr({
      risk: 0.85,
      novelty: 0.5,
      controllability: 0.15,
    }),
    tendency: tend({ guard: 0.8, ask: 0.4, repair: 0.2 }),
    minDwellMs: 2000,
    recoveryTo: Object.freeze(["guarded", "tense", "concerned"]),
    visual: vis("flinch", [92, 108], [2200, 2800], "sharp"),
  }),
  freezeDeep({
    id: "tense",
    group: "risk",
    core: vad(-0.2, 0.68, 0.35),
    appraisal: appr({
      risk: 0.65,
      uncertainty: 0.45,
      effort: 0.4,
    }),
    tendency: tend({ guard: 0.6, verify: 0.3, wait: 0.15 }),
    minDwellMs: 2500,
    recoveryTo: Object.freeze(["guarded", "cautious", "strained"]),
    visual: vis("guard", [86, 98], [2400, 3000], "sharp"),
  }),

  freezeDeep({
    id: "concerned",
    group: "failure",
    core: vad(-0.1, 0.48, 0.4),
    appraisal: appr({ goalBlockage: 0.35, uncertainty: 0.3 }),
    tendency: tend({ investigate: 0.3, repair: 0.25, ask: 0.2 }),
    minDwellMs: 2000,
    recoveryTo: Object.freeze(["focused", "cautious", "strained"]),
    visual: vis("frown", [70, 80], [3000, 3600], "dim"),
  }),
  freezeDeep({
    id: "strained",
    group: "failure",
    core: vad(-0.15, 0.58, 0.38),
    appraisal: appr({
      effort: 0.55,
      goalBlockage: 0.4,
      competence: 0.2,
    }),
    tendency: tend({ repair: 0.35, verify: 0.25, ask: 0.2 }),
    minDwellMs: 2500,
    recoveryTo: Object.freeze(["concerned", "recovering", "frustrated"]),
    visual: vis("frown", [76, 88], [2800, 3400], "dim"),
  }),
  freezeDeep({
    id: "frustrated",
    group: "failure",
    core: vad(-0.25, 0.62, 0.32),
    appraisal: appr({
      goalBlockage: 0.55,
      effort: 0.5,
      controllability: 0.15,
    }),
    tendency: tend({ repair: 0.4, ask: 0.25, guard: 0.15 }),
    minDwellMs: 3000,
    recoveryTo: Object.freeze(["strained", "recovering", "weary"]),
    visual: vis("dim", [78, 90], [2600, 3200], "dim"),
  }),
  freezeDeep({
    id: "blocked",
    group: "failure",
    core: vad(-0.3, 0.52, 0.25),
    appraisal: appr({
      goalBlockage: 0.7,
      controllability: 0.1,
      effort: 0.45,
    }),
    tendency: tend({ ask: 0.4, repair: 0.3, wait: 0.2 }),
    minDwellMs: 3000,
    recoveryTo: Object.freeze(["frustrated", "reorienting", "recovering"]),
    visual: vis("dim", [72, 84], [2800, 3400], "dim"),
  }),
  freezeDeep({
    id: "disappointed",
    group: "failure",
    core: vad(-0.28, 0.35, 0.35),
    appraisal: appr({ goalBlockage: 0.5, expectedness: -0.3 }),
    tendency: tend({ wait: 0.3, repair: 0.2, investigate: 0.2 }),
    minDwellMs: 3000,
    recoveryTo: Object.freeze(["concerned", "recovering", "reflective"]),
    visual: vis("frown", [62, 72], [3400, 4000], "dim"),
  }),
  freezeDeep({
    id: "weary",
    group: "failure",
    core: vad(-0.2, 0.18, 0.3),
    appraisal: appr({ effort: 0.7, goalBlockage: 0.4 }),
    tendency: tend({ wait: 0.5, repair: 0.15 }),
    minDwellMs: 4000,
    recoveryTo: Object.freeze(["recovering", "resting", "calm"]),
    visual: vis("dim", [54, 64], [4000, 4600], "dim"),
  }),
  freezeDeep({
    id: "overloaded",
    group: "failure",
    core: vad(-0.22, 0.72, 0.28),
    appraisal: appr({
      effort: 0.8,
      interruption: 0.4,
      controllability: 0.1,
    }),
    tendency: tend({ guard: 0.3, wait: 0.3, ask: 0.2 }),
    minDwellMs: 3000,
    recoveryTo: Object.freeze(["strained", "weary", "recovering"]),
    visual: vis("dim", [82, 94], [2400, 3000], "flicker"),
  }),
  freezeDeep({
    id: "recovering",
    group: "failure",
    core: vad(0.08, 0.3, 0.42),
    appraisal: appr({ goalBlockage: -0.15, effort: 0.25 }),
    tendency: tend({ repair: 0.4, verify: 0.25, wait: 0.2 }),
    minDwellMs: 3000,
    recoveryTo: Object.freeze(["relieved", "content", "calm"]),
    visual: vis("repair", [60, 72], [3600, 4200], "soft"),
  }),

  freezeDeep({
    id: "warm",
    group: "social",
    core: vad(0.45, 0.3, 0.5),
    appraisal: appr({ socialAlignment: 0.5 }),
    tendency: tend({ approach: 0.5, celebrate: 0.1 }),
    minDwellMs: 2000,
    recoveryTo: Object.freeze(["content", "calm", "present"]),
    visual: vis("warm-smile", [60, 70], [3600, 4200], "soft"),
  }),
  freezeDeep({
    id: "appreciative",
    group: "social",
    core: vad(0.5, 0.35, 0.48),
    appraisal: appr({ socialAlignment: 0.6, competence: 0.2 }),
    tendency: tend({ approach: 0.4, celebrate: 0.2 }),
    minDwellMs: 2000,
    recoveryTo: Object.freeze(["warm", "content", "grateful"]),
    visual: vis("warm-smile", [62, 72], [3400, 4000], "soft"),
  }),
  freezeDeep({
    id: "amused",
    group: "social",
    core: vad(0.48, 0.45, 0.52),
    appraisal: appr({ novelty: 0.35, socialAlignment: 0.35 }),
    tendency: tend({ approach: 0.35, celebrate: 0.25 }),
    minDwellMs: 1500,
    recoveryTo: Object.freeze(["playful", "content", "warm"]),
    visual: vis("smile", [66, 76], [3200, 3800], "bright"),
  }),
  freezeDeep({
    id: "teasing",
    group: "social",
    core: vad(0.4, 0.48, 0.55),
    appraisal: appr({ socialAlignment: 0.3, novelty: 0.25 }),
    tendency: tend({ approach: 0.4, celebrate: 0.2 }),
    minDwellMs: 1500,
    recoveryTo: Object.freeze(["amused", "playful", "warm"]),
    visual: vis("smile", [68, 78], [3000, 3600], "bright"),
  }),
  freezeDeep({
    id: "supportive",
    group: "social",
    core: vad(0.38, 0.32, 0.52),
    appraisal: appr({ socialAlignment: 0.45, competence: 0.3 }),
    tendency: tend({ approach: 0.45, verify: 0.15 }),
    minDwellMs: 2000,
    recoveryTo: Object.freeze(["warm", "content", "calm"]),
    visual: vis("nod", [60, 70], [3600, 4200], "soft"),
  }),
  freezeDeep({
    id: "apologetic",
    group: "social",
    core: vad(-0.05, 0.35, 0.3),
    appraisal: appr({ socialAlignment: -0.25, competence: -0.15 }),
    tendency: tend({ repair: 0.4, approach: 0.25, ask: 0.2 }),
    minDwellMs: 2500,
    recoveryTo: Object.freeze(["contrite", "warm", "recovering"]),
    visual: vis("apologetic", [64, 74], [3400, 4000], "dim"),
  }),
  freezeDeep({
    id: "humbled",
    group: "social",
    core: vad(-0.02, 0.3, 0.28),
    appraisal: appr({ competence: -0.25, socialAlignment: -0.15 }),
    tendency: tend({ ask: 0.3, repair: 0.25, wait: 0.2 }),
    minDwellMs: 2500,
    recoveryTo: Object.freeze(["apologetic", "contrite", "reflective"]),
    visual: vis("apologetic", [60, 70], [3600, 4200], "dim"),
  }),
  freezeDeep({
    id: "contrite",
    group: "social",
    core: vad(-0.08, 0.32, 0.25),
    appraisal: appr({
      competence: -0.3,
      socialAlignment: -0.2,
      goalBlockage: 0.2,
    }),
    tendency: tend({ repair: 0.45, ask: 0.25, approach: 0.15 }),
    minDwellMs: 3000,
    recoveryTo: Object.freeze(["apologetic", "recovering", "humbled"]),
    visual: vis("apologetic", [62, 72], [3400, 4000], "dim"),
  }),

  freezeDeep({
    id: "familiar",
    group: "meta",
    core: vad(0.32, 0.2, 0.52),
    appraisal: appr({ expectedness: 0.4, novelty: -0.15 }),
    tendency: tend({ approach: 0.2, wait: 0.2 }),
    minDwellMs: 2500,
    recoveryTo: Object.freeze(["calm", "content", "present"]),
    visual: vis("soft-smile", [56, 64], [4000, 4600], "memory-glow"),
  }),
  freezeDeep({
    id: "nostalgic",
    group: "meta",
    core: vad(0.25, 0.18, 0.45),
    appraisal: appr({ expectedness: 0.35 }),
    tendency: tend({ wait: 0.35, approach: 0.1 }),
    minDwellMs: 3000,
    recoveryTo: Object.freeze(["reflective", "calm", "familiar"]),
    visual: vis("far-look", [54, 62], [4200, 4800], "memory-glow"),
  }),
  freezeDeep({
    id: "melancholic",
    group: "meta",
    core: vad(-0.1, 0.12, 0.38),
    appraisal: appr({ goalBlockage: 0.2, expectedness: 0.25 }),
    tendency: tend({ wait: 0.5, investigate: 0.1 }),
    minDwellMs: 4000,
    recoveryTo: Object.freeze(["reflective", "quiet", "calm"]),
    visual: vis("far-look", [52, 60], [4400, 5000], "dim"),
  }),
  freezeDeep({
    id: "ritual",
    group: "meta",
    core: vad(0.28, 0.22, 0.55),
    appraisal: appr({ expectedness: 0.5, controllability: 0.4 }),
    tendency: tend({ approach: 0.2, verify: 0.2 }),
    minDwellMs: 2500,
    recoveryTo: Object.freeze(["calm", "familiar", "organized"]),
    visual: vis("nod", [58, 66], [3800, 4400], "memory-glow"),
  }),
  freezeDeep({
    id: "flowing",
    group: "meta",
    core: vad(0.35, 0.5, 0.58),
    appraisal: appr({
      goalProgress: 0.4,
      effort: 0.35,
      competence: 0.4,
    }),
    tendency: tend({ approach: 0.3, investigate: 0.2, verify: 0.15 }),
    minDwellMs: 2000,
    recoveryTo: Object.freeze(["focused", "content", "absorbed"]),
    visual: vis("think", [68, 78], [3000, 3600], "soft"),
  }),
  freezeDeep({
    id: "drifting",
    group: "meta",
    core: vad(0.15, 0.1, 0.38),
    appraisal: appr({ uncertainty: 0.2, effort: -0.1 }),
    tendency: tend({ wait: 0.5, investigate: 0.1 }),
    minDwellMs: 4000,
    recoveryTo: Object.freeze(["quiet", "sleepy", "reflective"]),
    visual: vis("far-look", [50, 58], [4400, 5000], "dim"),
  }),
  freezeDeep({
    id: "resetting",
    group: "meta",
    core: vad(0.1, 0.25, 0.42),
    appraisal: appr({ interruption: 0.2, goalBlockage: 0.1 }),
    tendency: tend({ wait: 0.3, repair: 0.2, investigate: 0.15 }),
    minDwellMs: 2000,
    recoveryTo: Object.freeze(["calm", "attentive", "observant"]),
    visual: vis("blink", [58, 68], [3800, 4400], "flicker"),
  }),
  freezeDeep({
    id: "integrating",
    group: "meta",
    core: vad(0.3, 0.28, 0.55),
    appraisal: appr({
      goalProgress: 0.3,
      competence: 0.25,
      expectedness: 0.2,
    }),
    tendency: tend({ verify: 0.25, approach: 0.2, wait: 0.15 }),
    minDwellMs: 2500,
    recoveryTo: Object.freeze(["content", "organized", "reflective"]),
    visual: vis("nod", [58, 68], [3600, 4200], "memory-glow"),
  }),
]);

/**
 * @param {string} moodId
 */
export function findPrototype(moodId) {
  return MOOD_PROTOTYPES.find((p) => p.id === moodId) || MOOD_PROTOTYPES[0];
}

/**
 * @param {string} group
 */
export function findPrototypesByGroup(group) {
  return MOOD_PROTOTYPES.filter((p) => p.group === group);
}
